swagger: "2.0"
info:
  title: User management API
  description: User management api description.
  version: 1.0.0
host: localhost:7001
basePath: /api
schemes:
  - http
paths:
  /groups:
    get:
      summary: Returns a list of available groups.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: Group object.
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 4
              name:
                type: string
                example: Group1
        400:
          description: The specified Group Id is invalid (e.g. not a number).
        404:
          description: A Group with the specified ID was not found.
        default:
          description: Unexpected error
  /groups/{id}:
    get:
      summary: Returns a group by ID.
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: OK
        400:
          description: The specified Group Id is invalid (e.g. not a number).
        404:
          description: A Group with the specified ID was not found.
        default:
          description: Unexpected error
  /users:
      get:
        summary: Returns a list of available Users.
        description: Optional extended description in Markdown.
        produces:
          - application/json
        responses:
          200:
            description: User object.
            schema:
              type: object
              
          400:
            description: The specified Group Id is invalid (e.g. not a number).
          404:
            description: A Group with the specified ID was not found.
          default:
            description: Unexpected error